sudo: required
services:
  - docker

before_install:
  - docker build -t avinashd30/client-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run avinashd30/client-react-test npm test -- --coverage

after_success:
  - docker build -t avinashd30/multi-container-client ./client
  - docker build -t avinashd30/multi-nginx ./nginx
  - docker build -t avinashd30/multi-server ./server
  - docker build -t avinashd30/multi-worker ./worker

#Log in to the docker CLI
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#Push the images to docker hup
- docker push avinashd30/multi-container-client
- docker push avinashd30/multi-nginx
- docker push avinashd30/multi-server
- docker push avinashd30/multi-worker
